# Generated by Django 5.2.4 on 2026-09-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_app', '0012_cafeteria_multi_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfood',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='利用者が確認済み'),
        ),
        migrations.AddField(
            model_name='customfood',
            name='nutrition_basis',
            field=models.CharField(choices=[('per_100g', '100gあたり'), ('per_serving', '1食あたり')], default='per_100g', max_length=20),
        ),
        migrations.AddField(
            model_name='customfood',
            name='serving_size_g',
            field=models.FloatField(blank=True, null=True, verbose_name='1食分重量(g)'),
        ),
        migrations.AddField(
            model_name='customfood',
            name='source',
            field=models.CharField(choices=[('manual', '手入力'), ('url', 'URL')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='customfood',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='customfood',
            constraint=models.CheckConstraint(condition=models.Q(('serving_size_g__isnull', True), ('serving_size_g__gt', 0), _connector='OR'), name='custom_food_serving_positive'),
        ),
        migrations.AddConstraint(
            model_name='customfood',
            constraint=models.CheckConstraint(condition=models.Q(('nutrition_basis', 'per_100g'), models.Q(('nutrition_basis', 'per_serving'), ('serving_size_g__isnull', False)), _connector='OR'), name='custom_food_serving_required'),
        ),
    ]
