# Generated by Django 5.2.4 on 2026-09-26 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__first__'),
        ('record_app', '0013_custom_food_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCreationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='mealcreationrequest',
            name='meal_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='record_app.mealrecord'),
        ),
        migrations.AddField(
            model_name='mealcreationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='mealcreationrequest',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='meal_request_user_key_unique'),
        ),
    ]
