# Generated by Django 5.2.4 on 2026-09-27 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record_app", "0014_meal_creation_request"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customfood",
            name="custom_food_serving_required",
        ),
        migrations.RemoveField(
            model_name="customfood",
            name="is_verified",
        ),
        migrations.AddField(
            model_name="customfood",
            name="nutrition_per_serving",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="custommenuitem",
            name="servings",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="mealrecorditem",
            name="servings",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="customfood",
            name="calcium_per_100g",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="カルシウム(mg)"
            ),
        ),
        migrations.AlterField(
            model_name="customfood",
            name="calories_per_100g",
            field=models.FloatField(
                blank=True, null=True, verbose_name="エネルギー(kcal)"
            ),
        ),
        migrations.AlterField(
            model_name="customfood",
            name="carbs_per_100g",
            field=models.FloatField(blank=True, null=True, verbose_name="炭水化物(g)"),
        ),
        migrations.AlterField(
            model_name="customfood",
            name="fat_per_100g",
            field=models.FloatField(blank=True, null=True, verbose_name="脂質(g)"),
        ),
        migrations.AlterField(
            model_name="customfood",
            name="fiber_per_100g",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="食物繊維(g)"
            ),
        ),
        migrations.AlterField(
            model_name="customfood",
            name="iron_per_100g",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="鉄(mg)"
            ),
        ),
        migrations.AlterField(
            model_name="customfood",
            name="protein_per_100g",
            field=models.FloatField(
                blank=True, null=True, verbose_name="たんぱく質(g)"
            ),
        ),
        migrations.AlterField(
            model_name="customfood",
            name="sodium_per_100g",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="ナトリウム(mg)"
            ),
        ),
        migrations.AlterField(
            model_name="customfood",
            name="vitamin_a_per_100g",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="ビタミンA(μg)"
            ),
        ),
        migrations.AlterField(
            model_name="customfood",
            name="vitamin_b1_per_100g",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="ビタミンB1(mg)"
            ),
        ),
        migrations.AlterField(
            model_name="customfood",
            name="vitamin_b2_per_100g",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="ビタミンB2(mg)"
            ),
        ),
        migrations.AlterField(
            model_name="customfood",
            name="vitamin_c_per_100g",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="ビタミンC(mg)"
            ),
        ),
        migrations.AlterField(
            model_name="custommenuitem",
            name="amount_grams",
            field=models.FloatField(blank=True, null=True, verbose_name="分量(g)"),
        ),
        migrations.AlterField(
            model_name="mealrecorditem",
            name="amount_grams",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="分量(g)",
            ),
        ),
    ]
